name = "PhaseMapping"
uuid = "82f33ccb-cd31-4690-8856-89c050ee4e49"
authors = ["Sebastian Ament <sebastianeament@gmail.com>"]
version = "0.1.0"

[deps]
BackgroundSubtraction = "9977cdcb-3521-4027-9f3f-3caff6505f42"
CompressedSensing = "adc28fdd-7b77-41a2-89a7-a1a193b336a0"
CovarianceFunctions = "b3329135-7958-41d4-bb02-e084c5a526bf"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KroneckerProducts = "1b19e153-50d3-4699-8064-93bcb9fb4fba"
LazyInverse = "d0afe1cb-6484-4949-b9e9-61bc645ed6c7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraExtensions = "cb114d4a-f1bd-499c-ad9e-7f2ed74575b9"
OptimizationAlgorithms = "5eef6961-c6df-46a7-ba44-0f01c6045f8f"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
WoodburyIdentity = "49563772-d9e4-48b4-a8b6-4cbe661ead9f"
